import pytest

@pytest.fixture()
def geometry_possible_datasets():
    return ['NEKTAR/GEOMETRY/MAPS/COMPOSITE', 'NEKTAR/GEOMETRY/MAPS/CURVE_EDGE', 'NEKTAR/GEOMETRY/MAPS/CURVE_FACE', 'NEKTAR/GEOMETRY/MAPS/DOMAIN',
            'NEKTAR/GEOMETRY/MAPS/HEX', 'NEKTAR/GEOMETRY/MAPS/PRISM', 'NEKTAR/GEOMETRY/MAPS/PYR', 'NEKTAR/GEOMETRY/MAPS/QUAD',
            'NEKTAR/GEOMETRY/MAPS/SEG', 'NEKTAR/GEOMETRY/MAPS/TET', 'NEKTAR/GEOMETRY/MAPS/TRI', 'NEKTAR/GEOMETRY/MAPS/VERT',
            'NEKTAR/GEOMETRY/MESH/COMPOSITE', 'NEKTAR/GEOMETRY/MESH/CURVE_EDGE', 'NEKTAR/GEOMETRY/MESH/CURVE_FACE',
            'NEKTAR/GEOMETRY/MESH/CURVE_NODES', 'NEKTAR/GEOMETRY/MESH/DOMAIN', 'NEKTAR/GEOMETRY/MESH/HEX', 'NEKTAR/GEOMETRY/MESH/PRISM',
            'NEKTAR/GEOMETRY/MESH/PYR', 'NEKTAR/GEOMETRY/MESH/QUAD', 'NEKTAR/GEOMETRY/MESH/SEG', 'NEKTAR/GEOMETRY/MESH/TET', 'NEKTAR/GEOMETRY/MESH/TRI',
            'NEKTAR/GEOMETRY/MESH/VERT']